#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
path[1,0]=~/bin

zstyle ':completion:*' special-dirs true
setopt dvorak

REPORTTIME=5
export OMP_NUM_THREADS=2
unalias gs
